name: Build Release

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build
        env:
          STATIC_EXPORT: "true"
          NEXT_PUBLIC_BASE_PATH: ""

      - run: node server/bundle.js

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install -g pkg

      - run: pkg server/keybr-server-bundle.js --targets node18-win-x64 --output server/keybr-server-win.exe
      - run: pkg server/keybr-server-bundle.js --targets node18-mac-x64 --output server/keybr-server-macos
      - run: pkg server/keybr-server-bundle.js --targets node18-linux-x64 --output server/keybr-server-linux

      - run: |
          cd server
          sha256sum keybr-server-* > SHA256SUMS.txt

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            server/keybr-server-win.exe
            server/keybr-server-macos
            server/keybr-server-linux
            server/SHA256SUMS.txt
          generate_release_notes: true
